apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xi1bckndd-python 
  janus-idp.io/tekton: xi1bckndd-python
  backstage.io/kubernetes-id: xi1bckndd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xi1bckndd-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml